version: '3'
services:
  # pumba:
  #   container_name: pumba
  #   image: alpine-pumba #image can be built with pumba/Dockerfile: docker build -t alpine-pumba .
  #   user: "root"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   networks:
  #     tx-network:
  #       ipv4_address: 10.6.0.20
  #     block-network:
  #       ipv4_address: 10.5.0.20        
  
  tx-node-1:
    container_name: tx-node-1
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ../.:/home/node/app
    command: 
      - /bin/bash
      - -c
      - |
        npm install
        tail -f /dev/null
    networks:
      tx-network:
        ipv4_address: 10.6.0.2
      block-network:
        ipv4_address: 10.5.0.10

  boot-node-1:
    image: plugnet/plugblockchain:1.0.0-rc2
    container_name: boot-node-1
    volumes: ["./data/boot-node-1:/mnt/node"]
    command:
      - /usr/local/bin/plug
      - --base-path=/mnt/node
      - --name=BOOT_NODE_1
      - --chain=dev
      - --validator
      - --unsafe-ws-external
      - --ws-port=9944
      - --unsafe-rpc-external
      - --rpc-cors=all
      - --telemetry-url=ws://cennznet-telemetry.centrality.me:1024
      - --bootnodes=/dns4/boot-node-3/tcp/30333/p2p/QmdoyqhDeYScKjNKZTK9Ru3KugwXxiUBaS2k9CESDbn3Be
      # Some arbitrary static bytes to set the libp2p public key
      - --node-key=D0FE7E415AA9BAD7605A6841E74C2E0BA72DA1367BBA28AA37DC044669D09858
      #- -l=sync=trace,babe=trace,gossip=trace,state-db=trace,state-trace=trace
      - --execution=Native
    networks:
      block-network:
        ipv4_address: 10.5.0.2

  boot-node-2:
    image: plugnet/plugblockchain:1.0.0-rc2
    container_name: boot-node-2
    volumes: ["./data/boot-node-2:/mnt/node"]
    command:
      - /usr/local/bin/plug
      - --base-path=/mnt/node
      - --name=BOOT_NODE_2
      - --chain=dev
      - --validator
      - --unsafe-ws-external
      - --ws-port=9944
      - --unsafe-rpc-external
      - --rpc-cors=all
      - --telemetry-url=ws://cennznet-telemetry.centrality.me:1024
      - --bootnodes=/dns4/boot-node-3/tcp/30333/p2p/QmdoyqhDeYScKjNKZTK9Ru3KugwXxiUBaS2k9CESDbn3Be
      # Some arbitrary static bytes to set the libp2p public key
      - --node-key=D0FE7E415AA9BAD7605A6841E74C2E0BA72DA1367BBA28AA37DC044669D09859
      #- -l=sync=trace,babe=trace,gossip=trace,state-db=trace,state-trace=trace
      - --execution=Native
    ports:
      - "9933:9933"
      - "9944:9944"
      - "30333:30333"
      - "8080:8000"
    networks:
      block-network:
        ipv4_address: 10.5.0.3

  boot-node-3:
    image: plugnet/plugblockchain:1.0.0-rc2
    container_name: boot-node-3
    volumes: ["./data/boot-node-3:/mnt/node"]
    command:
      - /usr/local/bin/plug
      - --base-path=/mnt/node
      - --chain=dev
      - --name=BOOT_NODE_3
      - --validator
      - --unsafe-ws-external
      - --ws-port=9944
      - --unsafe-rpc-external
      - --rpc-cors=all
      - --telemetry-url=ws://cennznet-telemetry.centrality.me:1024
      # Some arbitrary static bytes to set the libp2p public key
      - --node-key=D0FE7E415AA9BAD7605A6841E74C2E0BA72DA1367BBA28AA37DC044669D09860
      #- -l=sync=trace,babe=trace,gossip=trace,state-db=trace,state-trace=trace
      - --execution=Native
    ports:
      - "9945:9944"
    networks:
      block-network:
        ipv4_address: 10.5.0.4

  validator-node-1:
    image: plugnet/plugblockchain:1.0.0-rc2
    container_name: validator-node-1
    volumes: ["./data/validator-node-1:/mnt/node"]
    command:
      - /usr/local/bin/plug
      - --base-path=/mnt/node
      - --chain=dev
      - --bootnodes=/dns4/boot-node-1/tcp/30333/p2p/QmQmJTi2eDg53Ws3N5XaixMmiGCmhNNJX7bPBMirnD2JEs
      - --bob
      - --validator
      - --unsafe-ws-external
      - --rpc-cors=all
      - --telemetry-url=ws://cennznet-telemetry.centrality.me:1024
      #- -l=sync=trace,babe=trace,gossip=trace,state-db=trace,state-trace=trace
      - --execution=Native
    ports:
      - 9946:9944
    networks:
      block-network:
        ipv4_address: 10.5.0.5

  validator-node-2:
    image: plugnet/plugblockchain:1.0.0-rc2
    container_name: validator-node-2
    volumes: ["./data/validator-node-2:/mnt/node"]
    command:
      - /usr/local/bin/plug
      - --base-path=/mnt/node
      - --chain=dev
      - --bootnodes=/dns4/boot-node-2/tcp/30333/p2p/QmXocYwPfnfBr7NHmM6FssrD7gG7yRRouu2ESAizbBAKtW
      - --alice
      - --validator
      - --unsafe-ws-external
      - --rpc-cors=all
      - --telemetry-url=ws://cennznet-telemetry.centrality.me:1024
      #- -l=sync=trace,babe=trace,gossip=trace,state-db=trace,state-trace=trace
      - --execution=Native
    ports:
      - 9947:9944
    networks:
      block-network:
        ipv4_address: 10.5.0.6

  validator-node-3:
    image: plugnet/plugblockchain:1.0.0-rc2 
    container_name: validator-node-3
    volumes: ["./data/validator-node-3:/mnt/node"]
    command:
      - /usr/local/bin/plug
      - --base-path=/mnt/node
      - --chain=dev
      - --bootnodes=/dns4/boot-node-3/tcp/30333/p2p/QmdoyqhDeYScKjNKZTK9Ru3KugwXxiUBaS2k9CESDbn3Be
      - --charlie
      - --validator
      - --unsafe-ws-external
      - --rpc-cors=all
      - --telemetry-url=ws://cennznet-telemetry.centrality.me:1024
      #- -l=sync=trace,babe=trace,gossip=trace,state-db=trace,state-trace=trace
      - --execution=Native
    ports:
      - 9948:9944
    networks:
      block-network:
        ipv4_address: 10.5.0.7
      tx-network:
        ipv4_address: 10.6.0.03
      
  validator-node-4:
    image: plugnet/plugblockchain:1.0.0-rc2
    container_name: validator-node-4
    volumes: ["./data/validator-node-4:/mnt/node"]
    command:
      - /usr/local/bin/plug
      - --base-path=/mnt/node
      - --chain=dev
      - --bootnodes=/dns4/boot-node-1/tcp/30333/p2p/QmXocYwPfnfBr7NHmM6FssrD7gG7yRRouu2ESAizbBAKtW,/dns4/boot-node-2/tcp/30333/p2p/QmXocYwPfnfBr7NHmM6FssrD7gG7yRRouu2ESAizbBAKtW,/dns4/boot-node-3/tcp/30333/p2p/QmdoyqhDeYScKjNKZTK9Ru3KugwXxiUBaS2k9CESDbn3Be
      - --dave
      - --validator
      - --unsafe-ws-external
      - --rpc-cors=all
      - --telemetry-url=ws://cennznet-telemetry.centrality.me:1024
      #- -l=sync=trace,babe=trace,gossip=trace,state-db=trace,state-trace=trace
      - --execution=Native
    networks:
      block-network:
        ipv4_address: 10.5.0.8
      tx-network:
        ipv4_address: 10.6.0.04

  validator-node-5:
    image: plugnet/plugblockchain:1.0.0-rc2
    container_name: validator-node-5
    volumes: ["./data/validator-node-5:/mnt/node"]
    command:
      - /usr/local/bin/plug
      - --base-path=/mnt/node
      - --chain=dev
      - --bootnodes=/dns4/boot-node-1/tcp/30333/p2p/QmQmJTi2eDg53Ws3N5XaixMmiGCmhNNJX7bPBMirnD2JEs
      - --eve
      - --validator
      - --unsafe-ws-external
      - --rpc-cors=all
      - --telemetry-url=ws://cennznet-telemetry.centrality.me:1024
      #- -l=sync=trace,babe=trace,gossip=trace,state-db=trace,state-trace=trace
      - --execution=Native
    networks:
      block-network:
        ipv4_address: 10.5.0.9

networks:
    block-network:
      ipam:
        driver: default
        config:
          - subnet: "10.5.0.0/16"  
    tx-network:
      ipam:
        driver: default
        config:
          - subnet: "10.6.0.0/16"

