version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.12
    steps:
      - checkout
      - run:
          name: setup
          command: |
            npm install
      - run:
          name: ls
          command: |
            ls
      - run:
          name: test
          command: |
            npm test .
workflows:
  version: 2
  run-build:
    jobs:
      - build
